//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotoTouch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotoTouch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barcode_red {
            get {
                object obj = ResourceManager.GetObject("barcode_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RGB_Purple_Logo_Trans_Bk_small {
            get {
                object obj = ResourceManager.GetObject("RGB_Purple Logo_Trans Bk_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RGB_White_Logo_Trans_Bk200 {
            get {
                object obj = ResourceManager.GetObject("RGB_White Logo_Trans Bk200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudere l&apos;applicazione?.
        /// </summary>
        internal static string SAPP_CLOSE {
            get {
                return ResourceManager.GetString("SAPP_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile effettuare questa operazione durante la votazione..
        /// </summary>
        internal static string SAPP_CLOSE_ERR {
            get {
                return ResourceManager.GetString("SAPP_CLOSE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulazione di Voto.
        /// </summary>
        internal static string SAPP_DEMO {
            get {
                return ResourceManager.GetString("SAPP_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tocca per provare con 1 diritto di voto.
        /// </summary>
        internal static string SAPP_DEMO_1DIR {
            get {
                return ResourceManager.GetString("SAPP_DEMO_1DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tocca per provare con 3 diritti di voto.
        /// </summary>
        internal static string SAPP_DEMO_3DIR {
            get {
                return ResourceManager.GetString("SAPP_DEMO_3DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tocca per ritornare alla videata iniziale.
        /// </summary>
        internal static string SAPP_DEMO_3END {
            get {
                return ResourceManager.GetString("SAPP_DEMO_3END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Badge non abilitato al voto, chiamare operatore.
        /// </summary>
        internal static string SAPP_ERR_BDABIL {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDABIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge : .
        /// </summary>
        internal static string SAPP_ERR_BDG {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Badge Annullato.
        /// </summary>
        internal static string SAPP_ERR_BDGANN {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGANN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Errore nella conversione Badge.
        /// </summary>
        internal static string SAPP_ERR_BDGCONV {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGCONV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Il Badge non esiste.
        /// </summary>
        internal static string SAPP_ERR_BDGEST {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Codice Impianto diverso.
        /// </summary>
        internal static string SAPP_ERR_BDGIMP {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Badge non presente..
        /// </summary>
        internal static string SAPP_ERR_BDGPRES {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGPRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lettura codice di uscita (.
        /// </summary>
        internal static string SAPP_ERR_BDGUSCITA {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGUSCITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Il Badge ha già votato.
        /// </summary>
        internal static string SAPP_ERR_BDGVOT {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGVOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Tutti i soci hanno già votato.
        /// </summary>
        internal static string SAPP_ERR_BDGZERO {
            get {
                return ResourceManager.GetString("SAPP_ERR_BDGZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Voglio Votare.
        /// </summary>
        internal static string SAPP_NOVOTO {
            get {
                return ResourceManager.GetString("SAPP_NOVOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astenuto.
        /// </summary>
        internal static string SAPP_SKASTENUTOTUTTI {
            get {
                return ResourceManager.GetString("SAPP_SKASTENUTOTUTTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheda Bianca.
        /// </summary>
        internal static string SAPP_SKBIANCA {
            get {
                return ResourceManager.GetString("SAPP_SKBIANCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrario.
        /// </summary>
        internal static string SAPP_SKCONTRARIOTUTTI {
            get {
                return ResourceManager.GetString("SAPP_SKCONTRARIOTUTTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicazione già in esecuzione.
        /// </summary>
        internal static string SAPP_START_CTRL {
            get {
                return ResourceManager.GetString("SAPP_START_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemi nel caricamento della configurazione, verificare: \n - la mappatura dei dischi\n - il file votosegretospa.ini.
        /// </summary>
        internal static string SAPP_START_ERRCFG {
            get {
                return ResourceManager.GetString("SAPP_START_ERRCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema nel collegamento con la Pistola Barcode. La porta COM.
        /// </summary>
        internal static string SAPP_START_ERRCOM1 {
            get {
                return ResourceManager.GetString("SAPP_START_ERRCOM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  non esiste o presenta problemi.\n Il lettore barcode è stato disabilitato, premere Ctrl+S per configurarlo nuovamente.
        /// </summary>
        internal static string SAPP_START_ERRCOM2 {
            get {
                return ResourceManager.GetString("SAPP_START_ERRCOM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemi nella connessione al database.
        /// </summary>
        internal static string SAPP_START_ERRCONN {
            get {
                return ResourceManager.GetString("SAPP_START_ERRCONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemi nel caricamento configurazione db.
        /// </summary>
        internal static string SAPP_START_ERRDB {
            get {
                return ResourceManager.GetString("SAPP_START_ERRDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema nella mappatura dei dischi di rete. Il disco M: non è disponibile, effettuare la mappatura corretta e riavviare l&apos;applicazione.
        /// </summary>
        internal static string SAPP_START_ERRMAP {
            get {
                return ResourceManager.GetString("SAPP_START_ERRMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerco immagini....
        /// </summary>
        internal static string SAPP_START_IMGSEARCH {
            get {
                return ResourceManager.GetString("SAPP_START_IMGSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizializzo applicazione....
        /// </summary>
        internal static string SAPP_START_INIT {
            get {
                return ResourceManager.GetString("SAPP_START_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizializzo lettore barcode....
        /// </summary>
        internal static string SAPP_START_INITBARCODE {
            get {
                return ResourceManager.GetString("SAPP_START_INITBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carico configurazione....
        /// </summary>
        internal static string SAPP_START_INITCFG {
            get {
                return ResourceManager.GetString("SAPP_START_INITCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizializzo database....
        /// </summary>
        internal static string SAPP_START_INITDB {
            get {
                return ResourceManager.GetString("SAPP_START_INITDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carico preferenze....
        /// </summary>
        internal static string SAPP_START_INITPREF {
            get {
                return ResourceManager.GetString("SAPP_START_INITPREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizializzo Semaforo....
        /// </summary>
        internal static string SAPP_START_INITSEM {
            get {
                return ResourceManager.GetString("SAPP_START_INITSEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizializzo Touch....
        /// </summary>
        internal static string SAPP_START_INITTOUCH {
            get {
                return ResourceManager.GetString("SAPP_START_INITTOUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizializzo variabili....
        /// </summary>
        internal static string SAPP_START_INITVAR {
            get {
                return ResourceManager.GetString("SAPP_START_INITVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carico liste e votazioni....
        /// </summary>
        internal static string SAPP_START_INITVOT {
            get {
                return ResourceManager.GetString("SAPP_START_INITVOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 diritto di voto per.
        /// </summary>
        internal static string SAPP_VOTE_1DIRITTOPER {
            get {
                return ResourceManager.GetString("SAPP_VOTE_1DIRITTOPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Diritti di voto.
        /// </summary>
        internal static string SAPP_VOTE_D_DIRITTI {
            get {
                return ResourceManager.GetString("SAPP_VOTE_D_DIRITTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In voto:.
        /// </summary>
        internal static string SAPP_VOTE_D_RASO {
            get {
                return ResourceManager.GetString("SAPP_VOTE_D_RASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  diritti di voto per.
        /// </summary>
        internal static string SAPP_VOTE_DIRITTIPER {
            get {
                return ResourceManager.GetString("SAPP_VOTE_DIRITTIPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_icon {
            get {
                object obj = ResourceManager.GetObject("Save-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_icon1 {
            get {
                object obj = ResourceManager.GetObject("Save-icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Semaforo_red {
            get {
                object obj = ResourceManager.GetObject("Semaforo_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
